### ISSUE TITLE
Missing API Version from Standard Firmware release file

### ISSUE THREAD

**Issue by hstaab** [Th3Un1q3/flipp_pomodoro#326]
The releases are not pulling the API version into the file name any longer. For example:

<img width="1213" alt="Screenshot 2023-11-15 at 10 40 04 AM" src="https://github.com/Th3Un1q3/flipp_pomodoro/assets/12781573/b0fb580e-46f0-4907-a6b8-39c825007795">

Additionally this version isn't working with the latest dev release, though it could be a mistake i'm making as i'm installing flip_pomodoro for the first time.

Cheers

**Comment by hstaab** [comment]
Affecting v2.2.17 and a few of the last releases

**Comment by Th3Un1q3** [comment]
You're right. Probably build pipeline or tools were changed. Looking into it. Thank you!

**Comment by Th3Un1q3** [comment]
@hstaab Hello again! I appreciate your contribution in pointing out the issue.

I've made some updates to the build pipelines, specifically targeting release versions and enhancing API version detection. These changes have been tested on the unleashed 65 firmware, and I can confirm that they work seamlessly.

In light of these improvements, I'm marking the current issue as resolved. However, if you encounter any issues with the latest release, I'm here to help. Feel free to share your feedback, or open a follow-up issue if needed.

You can find the latest release [here](https://github.com/Th3Un1q3/flipp_pomodoro/releases/tag/v2.2.19).

Thank you once again for your collaboration!
